package compressor;

import java.io.UnsupportedEncodingException;

public class Compressed {
	public static void main(String[] args) throws UnsupportedEncodingException{
		//String lore = "Hello darkness my old friend . darkness darkness my old friend";
		String lore = "In the beginning were the titans — colossal metallic beings who brought order to the newborn universe by shaping the landscapes and races of millions of worlds. No one knows what came before them, but these benevolent rulers kept these worlds safe from the demons living in the interdimensional plane of the Twisting Nether. But it was a ceaseless task, and the struggle with such tireless evil depressed the titan champion Sargeras so completely he came to believe the conflict could only end in the destruction of the titans' work. And thus he abandoned his duty. He released and enlisted the very demons he'd spent millennia capturing and recruited the generals Kil'jaeden and Archimonde from the Eredar race to aid him in his Burning Crusade. One major Eredar leader, Velen, rejected his offer, and he and his followers left their homeworld to become the Draenei. More than 100,000 years ago, the rest of the titans found the world now known as Azeroth and created several races from earth and stone to complete their work there. But the vaguely Lovecraftian Old Gods wreaked havoc on the titans' plans, infecting these new races with the Curse of Flesh until, ages later, they degenerated into the fleshy dwarves, gnomes, mogu, and humans we know today. The Titans fought back, but they merely managed to imprison the Old Gods and subdue their elemental lords rather than fully end their threat. In time, the titans left. Yet the titans didn't create everything. The tauren and trolls (and, yes, pandaren) had roamed Azeroth's prairies and forests for ages before, and around 64,000 years ago, a band of dark trolls discovered the Well of Eternity, a pool of magic deep within Azeroth's only continent of Kalimdor. Some say it was actually the blood of a Titan who fell in the war with the Old Gods, but whatever its origins, over thousands of years its energies transformed the dark trolls into the night elves, who built a graceful civilization based on the consumption of the well's magic. This cozy existence ended 10,000 years ago when Azshara, the night elf queen, sought to use the well's great power to rid the world of what she considered the lesser races. Such power attracted Sargeras, who tricked Azshara into using the well to open a portal for his Burning Legion. The invasion failed through the efforts of the heroes Tyrande Whisperwind and Malfurion Stormrage, and Sargeras himself was trapped in the "
				+ "Twisting Nether as he passed through the closing portal. But the price was terrible. Its magic disrupted during the battle, the well collapsed and shattered Kalimdor into the multiple continents that comprise Azeroth today. Pained by the Sundering, the earthen dwarves fell into a long slumber. Azshara and her followers survived, but only through a pact with the Old Gods that twisted them into the amphibious naga. Malfurion's intractable brother Illidan created a new Well of Eternity with three vials of the old well's essence, but the fear of another Legion invasion led to his imprisonment and the creation of the tree Nordrassil to contain the well's power and heal the world. Centuries later, though, surviving members of the night elves' elite caste remained hopelessly addicted to magic. The other night elves banished them to the new eastern continent, where they became the light-skinned high elves and founded the new kingdom of Quel'thalas. They, too, had preserved a vial of the old well's waters in secret, and used it to create their Sunwell. The high elves spent centuries squabbling with the local trolls until at last they discovered a tribe of humans, descended from the flesh-cursed Vrykul, who had formed their first city-state of Strom for their own protection from the trolls. Desperate for allies, the elves taught 100 humans how to harness magic, and together they ended the troll domination of the eastern continent and forged a peaceful union that lasted almost 3,000 years. Around this time the dwarves awoke, now fully altered by the Curse of Flesh. The troll threat diminished, the younger mages founded the city of Dalaran and foolishly conjured demons in their curiosity. Fearing the consequences, Dalaran's leaders and the elves formed a secret council to elect and create a single Guardian of Tirisfal with the powers of both human and elven mages, thus acting as a godlike safeguard against Sargeras' demons. When one guardian grew too old or sick of fighting, they'd pass on the great power to a new guardian. That arrangement worked fine for almost two millennia, until the guardian Aegwynn decided to pass the power on to her child rather than the council's chosen successor. She fought demons with skill and passion like no other Guardian before her, even to the point of defeating an avatar of Sargeras himself. But Sargeras had planned this, and he transferred his spirit into Aegwynn and used "
				+ "it to possess her son, Medivh, years after he was born. Sargeras used Medivh to contact the far-off world of Draenor, where Kil'jaeden had found willing recruits for the Crusade in the form of the orcs who shared the planet with the draenei. The orcs had drank the demon Mannoroth's blood and became bloodthirsty warriors bound to his will; only a few refused, including the Frostwolf chief Durotan. Together, Medivh and the orc warlock Gul'dan created the Dark Portal between the two worlds and the first orcish invasion of Azeroth began. Medivh's apprentice Khadgar and the human champion Anduin Lothar realized Medivh's role in the conflict and decapitated him, thus inadvertently banishing Sargeras' spirit to the astral plane. For the next few years, however, the orcs poured in and the human city of Stormwind fell. Fearful of dissent, Gul'dan had Durotan assassinated, leaving his baby son Thrall to grow up as a slave to humans. Following years of struggle, the humans triumphed and the Dark Portal was destroyed. On Azeroth, humans herded the orcs into internment camps, where much of their bloodlust subsided. On Draenor, Gul'dan's former master Ner'zhul shattered the planet while trying to open portals to yet more worlds. Around a decade later, Thrall escaped his bondage and liberated the orcs as the leader of a new, hopeful Horde. He led his people across the sea to Kalimdor, where they befriended the tauren and the Darkspear trolls. Ner'zhul had tried to escape Draenor through a portal, but Kil'jaeden captured him and transformed him into the Lich King. He sent Ner'zhul and his new death knights to attempt the conquest Azeroth anew, this time with a plague that made victims rise as the Lich King's undead Scourge. With the leadership of the corrupted human prince Arthas, they crushed the main human kingdom of Lordaeron and razed Quel'thalas, cruelly resurrecting the ranger Sylvanas as a banshee. Arthas and the Scourge then defiled the Sunwell, summoning Archimonde and sacking Dalaran soon after. Most of the few remaining high elves, hungry for magic and facing bigotry after receiving naga assistance, ended their age-old alliance with the humans. The newly rediscovered night elves joined the alliance of humans and dwarves, and repelled Archimonde's assault on Nordrassil alongside Thrall's Horde. Elsewhere, the orcs' long curse ended after the orc Grom Hellscream killed Mannoroth, and Sylvanas shook off "
				+ "Arthas' control and founded a free undead society. Yet it was a bittersweet victory, as the recently freed Illidan Stormrage, far in the north, tried and failed to stop Arthas from merging with Ner'zhul and becoming the new Lich King. Thus begin the events of World of Warcraft, eventually leading to the Lich King's fall and renewed struggles with the Old Gods and the Burning Crusade. New wars and another world-shaping cataclysm followed, but it was also a great age of discovery, revealing Azeroth's Titanic origins and the long-forgotten continent of Pandaria.";
				
		//String lore = "champion Anduin Lothar realized Medivh's role in the conflict and decapitated him, thus inadvertently banishing Sargeras' spirit to the astral plane. For the next few years, however, the orcs poured in and the human city of Stormwind fell. Fearful of dissent, Gul'dan had Durotan assassinated, leaving his baby son Thrall to grow up as a slave to humans. Following years of struggle, the humans triumphed and the Dark Portal was destroyed. On Azeroth, humans herded the orcs into internment camps, where much of their bloodlust subsided. On Draenor, Gul'dan's former master Ner'zhul shattered the planet while trying to open portals to yet more worlds. Around a decade later, Thrall escaped his bondage and liberated the orcs as the leader of a new, hopeful Horde. He led his people across the sea to Kalimdor, where they befriended the tauren and the Darkspear trolls. Ner'zhul had tried to escape Draenor through a portal, but Kil'jaeden captured him and transformed him into the Lich King. He sent Ner'zhul and his new death knights to attempt the conquest Azeroth anew, this time with a plague that made victims rise as the Lich King's undead Scourge. With the leadership of the corrupted human prince Arthas, they crushed the main human kingdom of Lordaeron and razed Quel'thalas, cruelly resurrecting the ranger Sylvanas as a banshee. Arthas and the Scourge then defiled the Sunwell, summoning Archimonde and sacking Dalaran soon after. Most of the few remaining high elves, hungry for magic and facing bigotry after receiving naga assistance, ended their age-old alliance with the humans. The newly rediscovered night elves joined the alliance of humans and dwarves, and repelled Archimonde's assault on Nordrassil alongside Thrall's Horde. Elsewhere, the orcs' long curse ended after the orc Grom Hellscream killed Mannoroth, and Sylvanas shook off Arthas' control and founded a free undead society. Yet it was a bittersweet victory, as the recently freed Illidan Stormrage, far in the north, tried and failed to stop Arthas from merging with Ner'zhul and becoming the new Lich King. Thus begin the events of World of Warcraft, eventually leading to the Lich King's fall and renewed struggles with the Old Gods and the Burning Crusade. New wars and another world-shaping cataclysm followed, but it was also a great age of discovery, revealing Azeroth's Titanic origins and the long-forgotten continent of Pandaria.";
		lore = lore.replace(".", "");
		lore = lore.replace(",", "");
		lore = lore.replace("'", "");
		lore = lore.toLowerCase();

		/*Compressed comp = new Compressed(lore);
		System.out.println(comp.decompress());*/
		
		Compressed comp = new Compressed(lore);
		String deComp = comp.decompress();
		System.out.println(lore.equals(deComp));
		System.out.println(comp.data.length + " " + deComp.getBytes("UTF-8").length);

		/*byte[] a = lore.getBytes();
		lore = Subbing.sub(lore);
		byte[] b = linkToBytes(lore);
		String unlinked = unlink(b);
		System.out.println(Subbing.deSub(unlinked));
		System.out.println(a.length + " compressed to " + b.length + ". " + b.length/(float)a.length + " ratio.");*/
		
		/*String compressed = link(lore);
		String decompressed = unlink(compressed);
		System.out.println(decompressed);
		System.out.println(lore.length() + " compressed to " + compressed.length() + ". " + compressed.length()/(float)lore.length() + " ratio.");*/
	}
	
	private byte[] data;
	
	public Compressed(String in) throws UnsupportedEncodingException{
		data = Linking.linkToBytes(Subbing.sub(in));
	}
	public String decompress() throws UnsupportedEncodingException{
		return Subbing.deSub(Linking.unlink(data));
	}
}
